# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e017c2c229167fdc06b9798ef67429ab41be41ca12be04c7a3363e701bf780666f028d7a10096d0d85ea2e8ee4f81689cd552d62eb117fab85d8a2892d4a73c9

test:
  secret_key_base: 075893aa46f58a8a1b1eb892fb39d553bb63a57c0342b29f5db29725474e1d0db4af9a02d88481f1d9598157f2c209ebbc3e4d73b6db7109a7e25ef999c738ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
